os: linux
dist: focal
language: c
services:
    - docker
git:
    submodules: false
addons:
   apt:
    update: true
    packages:
    - clang-10
    - clang-tools-10
    - bison
    - flex
    - libjson-c-dev
    - autoconf-archive
    - libxen-dev
env:
  global:
    - CC=clang-10
    - CPP=clang-cpp-10
    - CXX=clang++-10
    - INSTALLDIR=$PWD/usr/local/
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/usr/local/lib
    - C_INCLUDE_PATH=$PWD/usr/local/include
    - CPLUS_INCLUDE_PATH=$PWD/usr/local/include
    - PKG_CONFIG_PATH="$PWD/usr/local/lib/pkgconfig/"
    - LDFLAGS="-L$PWD/usr/local/lib"
    - CFLAGS="-I$PWD/usr/local/include"

jobs:
    include:

#
# Coverity (broken at the moment on focal with clang-10)
#
    - if: branch = master
      env:
        - TEST="Coverity"
      addons:
        coverity_scan:
            project:
                name: "icedevml/drakvuf-coverity-test"
                description: "Build submitted via Travis CI"
            notification_email: ml@icedev.pl
            build_command_prepend: "cov-configure --comptype clangcc --compiler /usr/bin/clang-10; ./autogen.sh; ./configure --enable-debug; make clean"
            build_command:   "make"
            branch_pattern: master
        apt:
            update: true
            packages:
              - clang-10
              - clang-tools-10
              - bison
              - flex
              - libjson-c-dev
              - autoconf-archive
              - libxen-dev
      before_install:
        - sudo apt-get update
        - sudo apt-get -q -y install bison flex libjson-c-dev autoconf-archive libxen-dev clang-10
        - sudo sed -i 's/private __detail::__variant::_Variant_base<_Types...>/public __detail::__variant::_Variant_base<_Types...>/' /usr/include/c++/9/variant
        - git submodule update --init libvmi
        - cd libvmi
        - autoreconf -vif
        - ./configure --prefix=${INSTALLDIR} --disable-kvm --disable-file --disable-bareflank --disable-safety-checks
        - make
        - make install
        - cd ..
      script:
        - cat cov-int/build-log.txt
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
